# Generated by Django 3.1.6 on 2021-03-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0002_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='deliverable',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='requirements',
            field=models.TextField(null=True),
        ),
    ]
