# Generated by Django 3.1.6 on 2021-03-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0003_auto_20210317_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='order_reference',
            field=models.TextField(max_length=200),
        ),
    ]
